DjangoShop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('clients.urls', namespace='clients')),
    url(r'^', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^log_in/$', views.log_in, name="log_in"),
    url(r'^sign_up/$', views.sign_up, name="sign_up"),
    url(r'^welcome/$', views.welcome, name="welcome"),
    url(r'^logout$', auth_views.logout, {'next_page': '/'}, name="logout")
]

products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.hello_world, name='hello'),
    url(r'^product/(?P<pk>[0-9]+)/$', views.product_detail,
        name='views.product_detail'),
    url(r'^product/new/', views.new_product, name='new_product')
]

clients/models.py
from __future__ import unicode_literals
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=255)
    phone = models.IntegerField(unique=True)
    email = models.EmailField(max_length=255)
    address = models.CharField(max_length=255)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        ordering = ('id',)

products/models.py
from __future__ import unicode_literals
from django.db import models
from clients.models import Client


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(blank=True)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        ordering = ('id',)


class Favorite(models.Model):
    user = models.ForeignKey(Client)
    product = models.ForeignKey(Product)

    class Meta:
        verbose_name = 'Favorite'
        verbose_name_plural = 'Favorites'

    def __str__(self):
        return '%s likes %s' % (self.user.name, self.product.name)

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

clients/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login


def log_in(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('/welcome')
    return render(request, 'log_in.html', {})


def sign_up(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        user = User.objects.create_user(username=username,
                                        password=password)
        user.save()
        return redirect('/log_in/')
    return render(request, 'sign_up.html', {})


def welcome(request):
    return render(request, 'welcome.html', {})

products/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404
from .models import Product
from .forms import ProductForm


def hello_world(request):
    products = Product.objects.order_by('id')
    template = loader.get_template('index.html')
    context = {
        'products': products
    }
    return HttpResponse(template.render(context, request))


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    template = loader.get_template('product_detail.html')
    context = {
        'product': product
    }
    return HttpResponse(template.render(context, request))


def new_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = ProductForm()
    template = loader.get_template('new_product.html')
    context = {
        'form': form
    }
    return HttpResponse(template.render(context, request))

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>DjangoShop</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  <h1>Hellooooow!</h1>
  <a href="{% url 'new_product' %}">Add Product</a>
  <a href="{% url 'clients:log_in' %}">Log in</a>
  <a href="{% url 'clients:sign_up' %}">Sign up</a>
  <ul>
    {% for pr in products %}
      <li>
        <a href="{% url 'views.product_detail' pr.pk %}">
          {{ pr.name }}
        </a>
        | {{ pr.description }}
        <img src="{{ pr.image.url }}" alt="{{ pr.name }}"/>
      </li>
    {% endfor %}
  </ul>
</body>
</html>

templates/log_in.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login</title>
  </head>
  <body>
    <h1>Login</h1>
    <form action="" method="post">
      {% csrf_token %}
      <input type="text" name="username" required>
      <input type="password" name="password" required>
      <button type="submit">Login</button>
    </form>
  </body>
</html>

templates/new_product.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Product</title>
  </head>
  <body>
    <h1>New Product</h1>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create Product</button>
    </form>
  </body>
</html>

templates/product_detail.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>{{ product.name }}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    <h1>{{ product.name }}</h1>
    <h2>{{ product.description }}</h2>
    <p>
      {{ product.category }} | {{ product.price }}
    </p>
    <img src="{{ product.image.url }}" alt="{{ product.name }}" />
  </body>
</html>

templates/sign_up.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sign Up</title>
  </head>
  <body>
    <h1>Sign Up</h1>
    <form action="" method="post">
      {% csrf_token %}
      <input type="text" name="username" required>
      <input type="password" name="password" required>
      <button type="submit">Sign Up!</button>
    </form>
  </body>
</html>

templates/welcome.html
<h1>Welcome to DjangoShop!</h1>
<p>
  {% if user.is_authenticated %}
    Signed in as: {{ user.username }}
    |
    <a href="{% url "clients:logout" %}">Logout</a>
  {% else %}
    <a href="{% url "clients:log_in" %}">Log in</a>
  {% endif %}
</p>